library(readxl)
mydata<-read_xlsx('TeressaS_averages.xlsx',col_names = TRUE)
colnames(mydata)
names(mydata) 
model1 <- lm(cbind (ll_provision, net_interest_margin, noninterest_income, noninterest_expense, ROA, ROE) ~ RGDP + prime_rate + year, data = mydata)
model2 <- lm(cbind (first_ll_provision, first_net_interest_margin, first_noninterest_income, first_noninterest_expense, first_ROA, first_ROE) ~ RGDP + prime_rate + year, data = mydata)
model3 <- lm(cbind (second_ll_provision, second_net_interest_margin, second_noninterest_income, second_noninterest_expense, second_ROA, second_ROE) ~ RGDP + prime_rate + year, data = mydata)
model4 <- lm(cbind (third_ll_provision, third_net_interest_margin, third_noninterest_income, third_noninterest_expense, third_ROA, third_ROE) ~ RGDP + prime_rate + year, data = mydata)
model5 <- lm(cbind (fourth_ll_provision, fourth_net_interest_margin, fourth_noninterest_income, fourth_noninterest_expense, fourth_ROA, fourth_ROE) ~ RGDP + prime_rate + year, data = mydata)
summary(model1)
summary(model2)
summary(model3)
summary(model4)
summary(model5)

